const mongoose = require("mongoose");

const reviewSchema = new mongoose.Schema({
  review_id: { type: String, required: true, unique: true },
  hotel_id: { type: mongoose.Schema.Types.ObjectId, ref: "Hotel", required: true },
  hotel_name: { type: String },
  reviewer_name: { type: String, required: true },
  rating: { type: Number, required: true },
  raw_rating: { type: Number },
  raw_rating_scale: { type: Number },
  normalised_rating: { type: Number },
  review_text: { type: String, required: true },
  review_date: { type: String },
  review_date_parsed: { type: Date },
  stay_date: { type: String },
  platform: { type: String },
  platform_review_id: { type: String },
  room_number: { type: String },
  guest_email: { type: String },
  photo_urls: [String],
  country: { type: String },
  room_type: { type: String },
  stay_duration: { type: String },
  stay_date: { type: String },
  traveler_type: { type: String },
  reviewer_language: { type: String },
  loyalty_tier: { type: String },
  status: { type: String, default: "Pending" },
  is_processed: { type: Boolean, default: false },
  retry_count: { type: Number, default: 0 },
  sentiment: { type: String },
  sentiment_reason: { type: String },
  confidence: { type: Number },
  departments: [String],
  primary_department: { type: String },
  urgency: { type: String },
  urgency_reason: { type: String },
  issues: [String],
  positive_aspects: [String],
  requires_response: { type: Boolean },
  response_priority: { type: String },
  suggested_action: { type: String },
  suggested_reply: { type: String },
  is_factual_only: { type: Boolean },
  is_suspicious: { type: Boolean },
  suspicious_reason: { type: String },
  guest_emotion: { type: String },
  escalation_risk: { type: Boolean },
  escalation: { type: Boolean, default: false },
  escalation_reason: { type: String },
  escalation_threshold: { type: Number },
  needs_human_review: { type: Boolean },
  human_review_reason: { type: String },
  ai_error: { type: String },
  keyword_flagged: { type: Boolean, default: false },
  matched_keywords: [String],
  assignee_id: { type: String },
  assignee_name: { type: String, default: "Unassigned" },
  linked_ticket_id: { type: String },
  response_text: { type: String },
  response_tone: { type: String },
  submitted_by: { type: String },
  approved_by: { type: String },
  approved_at: { type: Number },
  classified_at: { type: Number },
  imported_at: { type: Number },
  internal_notes: [{
    text: String,
    author: String,
    timestamp: Number
  }],
  response_history: [{
    version: Number,
    text: String,
    tone: String,
    editor: String,
    timestamp: Number,
    is_approved: Boolean
  }],
  draft_history: [{
    version: Number,
    text: String,
    tone: String,
    model: { type: String, default: "llama-3.3-70b-versatile" },
    generated_by: { type: String, default: "ai" },
    editor: String,
    char_count: Number,
    timestamp: Number
  }],
  audit_log: [{
    action: String,
    actor: String,
    details: String,
    timestamp: Number
  }],
  staff_mentions: [String],
  flag_reason_category: { type: String },
  flagged_by: { type: String },
  flagged_at: { type: Number },
  flag_assigned_to: { type: String },
  flag_assigned_to_name: { type: String }
}, { timestamps: true });

module.exports = mongoose.model("Review", reviewSchema);
